version: '3.4'

services:
  modironline.log.db:
    image: mongo
  modironline.log.api:
    image: ${DOCKER_REGISTRY-}modironlinelogapi
    build:
      context: .
      dockerfile: Src/ModirOnline.Log/ModirOnline.Log.Api/Dockerfile
volumes:
  mongo_data: